channels:
- bioconda
- conda-forge
- defaults
dependencies:
- openjdk=11
- r-assertthat=0.2
# https://github.com/ContinuumIO/anaconda-issues/issues/4656
- r-base=3.5
- r-devtools=2.2
- r-httr=1.4
- r-irdisplay=0.7
- r-irkernel=1.0
- r-jpeg=0.1_8
- r-repr=1.1
- r-rjava=0.9
- r-roxygen2=7.0
- r-testthat=2.1
- r-tidyverse=1.3
- r-xml2=1.2
- r-drc=3.0_1
- pip:
  - jupyter-notebookparams
